apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seaweedfs-operator.fullname" . }}
  labels:
    {{- include "seaweedfs-operator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "seaweedfs-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "seaweedfs-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ if or .Values.image.credentials .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ include "seaweedfs-operator.pullSecretName" . }}
      {{ end }}
      serviceAccountName: {{ include "seaweedfs-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: seaweedfs-operator
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
        env:
        {{- if eq .Values.webhook.enabled false }}
        - name: ENABLE_WEBHOOKS
          value: "false"
        {{- end }}
        ports:
        - name: {{ .Values.port.name }}
          containerPort: {{ .Values.port.number }}
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.webhook.enabled }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.webhook.enabled }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "seaweedfs-operator.fullname" . }}-webhook-server-cert
          items:
          - key: cert
            path: tls.crt
          - key: key
            path: tls.key
      {{- end }}
