run:
  timeout: 15m
  allow-parallel-runners: false  # Disable parallel runners to save memory
  go: "1.22"
  concurrency: 1  # Single thread to minimize memory usage

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  max-issues-per-linter: 50  # Limit issues per linter to save memory
  max-same-issues: 10        # Limit same issues to save memory
  exclude-dirs:
    - bin
    - .git
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"  # Skip generated protobuf files
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - path: "internal/controller/*_test.go"
      linters:
        - gocyclo  # Test functions can be complex due to table-driven tests
        - goconst  # Test files often have repeated test strings
linters:
  disable-all: true
  enable:
    # Essential linters only to reduce memory usage
    - errcheck      # Check for unchecked errors
    - gofmt         # Code formatting
    - govet         # Go vet analysis
    - staticcheck   # Advanced static analysis
    - typecheck     # Type checking
    - unused        # Find unused code
