run:
  timeout: 20m
  allow-parallel-runners: false  # Disable parallel runners to save memory
  go: "1.22"
  concurrency: 1  # Single thread to minimize memory usage
  modules-download-mode: readonly  # Don't download modules
  build-tags: []  # No build tags to reduce complexity

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  max-issues-per-linter: 20  # Severely limit issues per linter
  max-same-issues: 5         # Severely limit same issues
  exclude-dirs:
    - bin
    - .git
    - vendor
    - test/e2e         # Skip e2e tests to save memory
    - deploy           # Skip deployment files
    - .github          # Skip GitHub workflows
  exclude-files:
    - ".*\\.pb\\.go$"     # Skip generated protobuf files
    - ".*_test\\.go$"     # Skip all test files to save memory
    - "zz_generated.*"    # Skip generated files
  # Minimal exclude rules since we skip test files entirely
linters:
  disable-all: true
  enable:
    # Absolute minimum linters to prevent OOM kills
    - gofmt         # Code formatting (lightweight)
    - govet         # Go vet analysis (essential)
    - typecheck     # Type checking (critical)
