apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  labels:
    app.kubernetes.io/name: seaweed
    app.kubernetes.io/instance: seaweed-sample
    app.kubernetes.io/part-of: seaweedfs-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: seaweedfs-operator
  name: seaweed-sample
spec:
  image: chrislusf/seaweedfs:latest

  # Master servers
  master:
    replicas: 1
    volumeSizeLimitMB: 1024

  # Volume servers
  volume:
    replicas: 1

  # Filer servers with S3 and embedded IAM
  filer:
    replicas: 1
    s3:
      enabled: true
    iam: true  # Enable IAM service embedded with filer
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
    service:
      type: ClusterIP

  # Standalone IAM configuration (used for port setting when embedded)
  iam:
    port: 8111  # Custom port for IAM service
