apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-topology
  namespace: default
spec:
  # SeaweedFS image
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  # Master configuration with 210 replication
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
    # Set default replication to 210 (2 copies in different datacenters, 1 copy in different rack, 0 copies in same rack)
    defaultReplication: "210"

  # Volume server configuration with topology information
  volume:
    replicas: 6  # Deploy 6 volume servers across different racks/datacenters
    requests:
      storage: 10Gi
    # Topology configuration
    rack: "rack1"
    dataCenter: "dc1"
    # Node selector to ensure pods are placed on nodes with appropriate labels
    nodeSelector:
      seaweedfs/datacenter: "dc1"
      seaweedfs/rack: "rack1"

  # Filer configuration
  filer:
    replicas: 2
    s3:
      enabled: true
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"

---
# Additional Seaweed instances for other racks/datacenters
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-topology-dc1-rack2
  namespace: default
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  # Only deploy volume servers for this instance
  master:
    replicas: 0  # Don't deploy masters, use the main instance

  volume:
    replicas: 3
    requests:
      storage: 10Gi
    rack: "rack2"
    dataCenter: "dc1"
    nodeSelector:
      seaweedfs/datacenter: "dc1"
      seaweedfs/rack: "rack2"

  filer:
    replicas: 0  # Don't deploy filers, use the main instance

---
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-topology-dc2-rack1
  namespace: default
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  # Only deploy volume servers for this instance
  master:
    replicas: 0  # Don't deploy masters, use the main instance

  volume:
    replicas: 3
    requests:
      storage: 10Gi
    rack: "rack1"
    dataCenter: "dc2"
    nodeSelector:
      seaweedfs/datacenter: "dc2"
      seaweedfs/rack: "rack1"

  filer:
    replicas: 0  # Don't deploy filers, use the main instance
