apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
  namespace: default
spec:
  # Add fields here
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1
  hostSuffix: seaweed.abcdefg.com
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 2
    s3:
      enabled: true
      identities: 
        - name: "user1"
          actions: 
            - "Admin"
          credentials:
            - accessKey: "testkey"
              secretKey: "testpass"
            - accessKey: "testkey2"
              secretKey: "testpass2"
        - name: "user2"
          actions: 
            - "Read"
            - "List"
            - "Write"
          credentials:
            - accessKey: "testkey3"
              secretKey: "testpass3"
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
