# Example: Migration from legacy volume section to volumeTopology
# This shows how to disable the old volume section and use the new topology approach

apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-migration-example
  namespace: default
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  # Master configuration
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
    defaultReplication: "210"  # Enable 210 replication

  # DISABLE legacy volume section by setting replicas to 0
  # This is now allowed after the validation fix
  volume:
    replicas: 0  # ✅ Now valid! Previously required minimum: 1
    requests:
      storage: 10Gi
    # You can still specify other volume settings here as defaults
    # but they won't be used since replicas: 0

  # NEW: Use volumeTopology for structured deployment
  volumeTopology:
    dc1-rack1:
      replicas: 3
      requests:
        storage: 10Gi
      rack: "rack1"
      dataCenter: "dc1"
      nodeSelector:
        topology.kubernetes.io/zone: "us-west-2a"
        seaweedfs/datacenter: "dc1"
        seaweedfs/rack: "rack1"
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"

    dc1-rack2:
      replicas: 2
      requests:
        storage: 10Gi
      rack: "rack2"
      dataCenter: "dc1"
      nodeSelector:
        topology.kubernetes.io/zone: "us-west-2b"
        seaweedfs/datacenter: "dc1"
        seaweedfs/rack: "rack2"
      resources:
        limits:
          cpu: "1.5"
          memory: "3Gi"
        requests:
          cpu: "500m"
          memory: "1.5Gi"

    dc2-rack1:
      replicas: 3
      requests:
        storage: 15Gi  # Different storage size for this datacenter
      rack: "rack1"
      dataCenter: "dc2"
      nodeSelector:
        topology.kubernetes.io/zone: "us-east-1a"
        seaweedfs/datacenter: "dc2"
        seaweedfs/rack: "rack1"
      storageClassName: "fast-ssd"  # Use faster storage
      compactionMBps: 100
      maxVolumeCounts: 100

  # Filer configuration
  filer:
    replicas: 2
    s3:
      enabled: true
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
