name: "helm: publish charts"
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.5)'
        required: true
        type: string

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "chrislusf"
          git config user.email "chrislusf@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Determine tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Detected tag: $TAG"

      - name: Set appVersion in Chart.yaml to match tag
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          echo "Setting appVersion to: $TAG"
          sed -i "s/appVersion: .*/appVersion: \"$TAG\"/" deploy/helm/Chart.yaml

      - name: Debug chart structure
        run: |
          echo "Chart.yaml content:"
          cat deploy/helm/Chart.yaml
          echo -e "\nLinting chart:"
          helm lint deploy/helm
          echo -e "\nPackaging chart for verification:"
          helm package deploy/helm --debug

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deploy
